### ISSUE TITLE
60 lines? I don't know. Do what you need to do, but I have never seen a good type system change that couldn't be well-motivated by a single screenful of code.
I try somting

### ISSUE THREAD

**Issue by Remco0570** [Remco0570/Remco#13]
60 lines? I don't know. Do what you need to do, but I have never seen a good type system change that couldn't be well-motivated by a single screenful of code.

What does Effect-TS lose if it adds the non-predicate overload?

_Originally posted by @RyanCavanaugh in https://github.com/microsoft/TypeScript/issues/60741#issuecomment-2542389944_

**Comment by RyanCavanaugh** [comment]
?

**Comment by akomm** [comment]
Confused
